name: Pull latest images to GHCR from Docker Hub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'  # 每月1号 00:00 执行

jobs:
  pull-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 登录到 GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 创建镜像存储目录
        run: mkdir -p docker-images

      - name: 批量处理 Docker 镜像
        run: |
          # 转换 GitHub 用户名为小写
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          
          # 定义要拉取的镜像列表
          declare -A images=(
            ["mongo"]="latest"
            ["redis"]="latest"
            ["nginx"]="stable"
            ["ubuntu"]="latest"
            ["postgres"]="latest"
            ["dart"]="latest"
            ["swift"]="latest"
            ["sickcodes/docker-osx"]="latest"
          )
          
          # 遍历并处理每个镜像
          for image in "${!images[@]}"; do
            tag="${images[$image]}"
            echo "Processing $image:$tag..."
            
            # 拉取镜像
            docker pull $image:$tag
            
            # 推送到 GHCR (使用小写用户名)
            docker tag $image:$tag ghcr.io/$OWNER/$image:$tag
            docker push ghcr.io/$OWNER/$image:$tag
            
            # 设置包为公开访问
            # gh api \
            #   --method PATCH \
            #   -H "Accept: application/vnd.github.v3+json" \
            #   /orgs/$OWNER/packages/container/$image/visibility \
            #   -f visibility='public'
              
            # 保存镜像到文件
            # echo "Saving $image:$tag to file..."
            # docker save $image:$tag | gzip > docker-images/$image-$tag.tar.gz
          done

      # - name: 提交镜像文件到仓库
      #   run: |
      #     git config --global user.name "GitHub Actions Bot"
      #     git config --global user.email "actions@github.com"
          
      #     git lfs track "*.tar.gz"
      #     git add docker-images/
      #     git commit -m "更新 Docker 镜像文件 $(date +'%Y-%m-%d')"
      #     git push
