name: Pull an image to GHCR from Docker Hub

on:
  # 手动触发工作流
  workflow_dispatch:
    inputs:
      image_name:
        description: '需要拉取的镜像名称 (例如: mongo)'
        required: true
      image_tag:
        description: '镜像标签 (例如: latest)'
        required: true
        default: 'latest'

jobs:
  pull-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 登录到 GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 拉取并推送 Docker 镜像
        env:
          OWNER: ${{ github.repository_owner }}
          REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.event.inputs.image_name }}
          IMAGE_TAG: ${{ github.event.inputs.image_tag }}
        run: |
          # 转换组织名为小写
          OWNER_LOWER=$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')
          
          # 拉取原始镜像
          docker pull $IMAGE_NAME:$IMAGE_TAG
          
          # 标记为 GHCR 镜像 (使用小写组织名)
          docker tag $IMAGE_NAME:$IMAGE_TAG $REGISTRY/$OWNER_LOWER/$IMAGE_NAME:$IMAGE_TAG
          
          # 推送到 GHCR
          docker push $REGISTRY/$OWNER_LOWER/$IMAGE_NAME:$IMAGE_TAG
